name: Update Superproject Submodule

on:
  push:
    branches:
      - main

jobs:
  update-superproject:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Generate GitHub App Installation Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation_retrieval_mode: repository
          installation_retrieval_payload: Zarritas/Clubion

      - name: Clone superproject and update submodule
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://github.com/Zarritas/Clubion.git
          cd Clubion

          git submodule update --init --recursive
          cd clubion_backend
          git fetch
          git checkout $GITHUB_SHA
          cd ..

          git add modulo
          git commit -m "chore: update submodule to $GITHUB_SHA"
          git push
